#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#curl -sSL http://bit.ly/2ysbOFE | bash -s 1.3.0 1.3.0 0.4.13
version: '2'

networks:
  kyc:
services:

  ca.bnk1.kyc.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.bnk1.kyc.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bnk1.kyc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6e07014eb28d05cd22a44ed62def446a46e00f12a12e4362295cdde68a7ddb81_sk
    ports:
      - "5054:7054"
    command: sh -c 'fabric-ca-server start -b bnk1admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/bnk1.kyc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.bnk1.kyc.com
    networks:
      - kyc
  ca.bnk2.kyc.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.bnk2.kyc.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bnk2.kyc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/bcab3afd3c455c38afcb171a027f29d3c33ba5b95e8ac3d54aea3f72a8f3f131_sk
    ports:
      - "6054:7054"
    command: sh -c 'fabric-ca-server start -b bnk2admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/bnk2.kyc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.bnk2.kyc.com
    networks:
      - kyc
  ca.rgl1.kyc.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.rgl1.kyc.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.rgl1.kyc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/09c9e8ed1b5d86f38afdb22b57e01c1c0a903689c53d4235c93dc67fa4a985cc_sk
    ports:
    
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b rgl1admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/rgl1.kyc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.rgl1.kyc.com
    networks:
      - kyc
      
  orderer.kyc.com:
    container_name: orderer.kyc.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/commongenesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/kyc.com/orderers/orderer.kyc.com/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/bnk1.kyc.com/peers/peer0.bnk1.kyc.com/:/etc/hyperledger/msp/peerbnk1
    networks:
      - kyc

  peer0.bnk1.kyc.com:
    container_name: peer0.bnk1.kyc.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.bnk1.kyc.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=bnk1msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.bnk1.kyc.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_kyc
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 5051:7051
      - 5053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/bnk1.kyc.com/peers/peer0.bnk1.kyc.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/bnk1.kyc.com/users:/etc/hyperledger/msp/users
        - ./config/:/etc/hyperledger/configtx
        # - ./chaincode/:/opt/gopath/src/github.com/
    depends_on:
      - orderer.kyc.com
      - couchdb0
    networks:
      - kyc
  peer0.bnk2.kyc.com:
    container_name: peer0.bnk2.kyc.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.bnk2.kyc.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=bnk2msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.bnk2.kyc.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_kyc
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 6051:7051
      - 6053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/bnk2.kyc.com/peers/peer0.bnk2.kyc.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/bnk2.kyc.com/users:/etc/hyperledger/msp/users
        - ./config/:/etc/hyperledger/configtx
        # - ./chaincode/:/opt/gopath/src/github.com/
    depends_on:
      - orderer.kyc.com
      - couchdb1
    networks:
      - kyc
  peer0.rgl1.kyc.com:
    container_name: peer0.rgl1.kyc.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.rgl1.kyc.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=rgl1msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.rgl1.kyc.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_kyc
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/rgl1.kyc.com/peers/peer0.rgl1.kyc.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/rgl1.kyc.com/users:/etc/hyperledger/msp/users
        - ./config/:/etc/hyperledger/configtx
        # - ./chaincode/:/opt/gopath/src/github.com/
    depends_on:
      - orderer.kyc.com
      - couchdb2
    networks:
      - kyc
  
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:$THIRDPARTYIMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - kyc
  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:$THIRDPARTYIMAGE_TAG
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - kyc
  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb:$THIRDPARTYIMAGE_TAG
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
    - kyc
    
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.bnk1.kyc.com:7051
      - CORE_PEER_LOCALMSPID=bnk1msp
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bnk1.kyc.com/users/Admin@bnk1.kyc.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./config/:/etc/hyperledger/configtx
        - ./chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - kyc
    depends_on:
      - orderer.kyc.com
      - peer0.bnk1.kyc.com
      - couchdb0
      - peer0.bnk2.kyc.com
      - couchdb1      
      - peer0.rgl1.kyc.com
      - couchdb2
